# Generated by Django 2.2.3 on 2019-07-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wallPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallPost_text', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='Date Posted')),
            ],
        ),
    ]
