# Generated by Django 2.2.3 on 2019-07-30 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcementWall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallpost',
            old_name='wallPost_text',
            new_name='wallpost_text',
        ),
    ]
