# Generated by Django 2.2.3 on 2019-07-30 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcementWall', '0002_auto_20190730_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallpost',
            old_name='wallpost_text',
            new_name='wallpost_title',
        ),
    ]
