# Generated by Django 2.2.3 on 2019-07-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcementWall', '0003_auto_20190730_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpost',
            name='wallpost_text',
            field=models.TextField(default='N/A', max_length=5000),
            preserve_default=False,
        ),
    ]
